# Generated by Django 4.2.23 on 2026-03-20 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campeonato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data", models.DateField()),
                (
                    "data_inscricao",
                    models.DateTimeField(
                        help_text="Informe a data limite para inscrição, ex: 2024-12-31",
                        verbose_name="data de inscrição",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                (
                    "sequencia",
                    models.PositiveSmallIntegerField(
                        help_text="Informe a sequência da etapa, ex: 1 para final, 2 para semifinal, 3 para quartas de final, etc.",
                        verbose_name="sequência da etapa",
                    ),
                ),
                (
                    "quantidade_jogos",
                    models.PositiveSmallIntegerField(
                        help_text="Informe quantos jogos tem nesta etapa, ex: Quartas de final tem 4 jogos.",
                        verbose_name="quantidade de jogos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_time",
                    models.CharField(
                        help_text="Informe o nome do time, ex: Time Alpha",
                        max_length=60,
                        verbose_name="Nome do time",
                    ),
                ),
                ("confirmada", models.BooleanField(default=False)),
                ("confirmada_em", models.DateTimeField(blank=True, null=True)),
                ("inscrito_em", models.DateTimeField(auto_now_add=True)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campeonato.campeonato",
                    ),
                ),
                (
                    "inscrito_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Exemplo: LOL, CS, Fifa, etc.", max_length=60
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        blank=True,
                        help_text="Informe a data e hora do jogo, ex: 2024-12-31 18:00",
                        null=True,
                        verbose_name="data e hora do jogo",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        help_text="Informe o resultado do jogo, ex: 2-1",
                        max_length=30,
                        null=True,
                        verbose_name="resultado do jogo",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campeonato.etapa",
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campeonato.modalidade",
                    ),
                ),
                (
                    "time_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_1",
                        to="campeonato.inscricao",
                    ),
                ),
                (
                    "time_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_2",
                        to="campeonato.inscricao",
                    ),
                ),
                (
                    "vencedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vencedor",
                        to="campeonato.inscricao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                (
                    "id_jogador",
                    models.CharField(
                        help_text="Informe o id do jogador, ex: nome#1234",
                        max_length=100,
                        verbose_name="ID do jogador",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campeonato.campus",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inscricao",
            name="jogadores",
            field=models.ManyToManyField(to="campeonato.jogador"),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="campeonato.modalidade"
            ),
        ),
        migrations.AddField(
            model_name="campeonato",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="campeonato.campus"
            ),
        ),
        migrations.AddField(
            model_name="campeonato",
            name="modalidades",
            field=models.ManyToManyField(to="campeonato.modalidade"),
        ),
    ]
