# Generated by Django 5.2.11 on 2026-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='campeonato',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='inscrito_por',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='jogadores',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='time_2',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='vencedor',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='time_1',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='modalidade',
        ),
        migrations.DeleteModel(
            name='Campeonato',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Etapa',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
        migrations.DeleteModel(
            name='Modalidade',
        ),
    ]
