# Generated by Django 5.2.11 on 2026-04-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_curso_remove_inscricao_campeonato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
