# Generated by Django 5.2.11 on 2026-04-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0003_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campeonato.professor'),
        ),
    ]
