# Generated by Django 5.2.11 on 2026-04-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0006_aluno_matricula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'turma')},
        ),
    ]
