"""
Django settings for naes2026 project.

Generated by 'django-admin startproject' using Django 5.2.11.
"""

from pathlib import Path

# Caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# Segurança
SECRET_KEY = "django-insecure-89-9ta=@&@$53*n!o&(2p@07k51kywvee*d+z+9n2abl)6+29s"

DEBUG = True

ALLOWED_HOSTS = ["*"]


# =========================
# APPS INSTALADOS
# =========================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Seus apps
    "website.apps.WebsiteConfig",
    "curso.apps.CursoConfig",
    # Crispy Forms
    "crispy_forms",
    "crispy_bootstrap5",
]


# =========================
# MIDDLEWARE
# =========================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================
# URLS
# =========================

ROOT_URLCONF = "naes2026.urls"


# =========================
# TEMPLATES
# =========================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================
# WSGI
# =========================

WSGI_APPLICATION = "naes2026.wsgi.application"


# =========================
# BANCO DE DADOS - POSTGRESQL
# =========================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "neondb",
        "USER": "neondb_owner",
        "PASSWORD": "npg_gOFLJpW2Ci6B",
        "HOST": "ep-bitter-tree-ac9wfji1-pooler.sa-east-1.aws.neon.tech",
        "PORT": "5432",
    }
}


# =========================
# VALIDAÇÃO DE SENHA
# =========================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =========================
# INTERNACIONALIZAÇÃO
# =========================

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# =========================
# ARQUIVOS ESTÁTICOS
# =========================

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static"]


# =========================
# PADRÃO DE CHAVE PRIMÁRIA
# =========================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================
# CRISPY FORMS
# =========================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
